### ISSUE TITLE
new Haiku H/I - light not detected

### ISSUE THREAD

**Issue by speedlimiter** [oogje/homebridge-i6-bigAssFans#14]
Got my first Haiku H/I with light kit (Haiku Schlafzimmer) two years ago. This one has an IR remote. It works flawlessly with your plugin after updating it to the latest i6-compatible firmware.

Bought a second Haiku H/I with light kit (Haiku Wohnzimmer) a month ago. It has a smaller Bluetooth remote. Adding it to my config doesn’t show the light switch. It’s also on the latest firmware (3.1.0).

[13/08/2022, 20:07:31] [BigAssFans-i6] dblog progress(0/0) Haiku Schlafzimmer - product type: Haiku H/I Series (0x48, 0x61, 0x69, 0x6b, 0x75, 0x20, 0x48, 0x2f, 0x49, 0x20, 0x53, 0x65, 0x72, 0x69, 0x65, 0x73)
[13/08/2022, 20:07:31] [BigAssFans-i6] dblog progress(0/0) Haiku Schlafzimmer - firmware: 3.1.0
[13/08/2022, 20:07:31] [BigAssFans-i6] Haiku Wohnzimmer - no light detected
[13/08/2022, 20:07:31] [BigAssFans-i6] dblog progress(0/0) Haiku Wohnzimmer - product type: Haiku H/I Series (0x48, 0x61, 0x69, 0x6b, 0x75, 0x20, 0x48, 0x2f, 0x49, 0x20, 0x53, 0x65, 0x72, 0x69, 0x65, 0x73)
[13/08/2022, 20:07:31] [BigAssFans-i6] dblog progress(0/0) Haiku Wohnzimmer - firmware: 3.1.0
[13/08/2022, 20:07:32] [BigAssFans-i6] Haiku Schlafzimmer - light detected

**Comment by oogje** [comment]
Are the light kits on the two fans the same or does one have, for instance, an uplight?

**Comment by speedlimiter** [comment]
Both are the same, LED light kit pointing downwards.

**Comment by oogje** [comment]
If you remove the first fan from the config file and restart does it then recognize the 2nd fan's light?

**Comment by speedlimiter** [comment]
Removed the first fan and restarted Homebridge. It’s still visible in the accessories page (in Homebridge UI) but the config correctly only shows the second fan. Is this some sort of caching?

The light of the second fan doesn’t show up.

What I noticed. There is a hardware difference between the two fans. The first fan has blue dots which are pointing down to show the different speed setting. The newer one doesn’t have them. It only lights up entirely to indicate that it has received the command.

When I’m using the BAF-app it briefly shows the i6 glyph for the second fan before switching to what’s recognizable as a Haiku. If I’m fast enough I can read „Gen 3 device“ as product type instead of Haiku H/I. But it’s definitely not the new Haiku which was announced a few days ago.

**Comment by oogje** [comment]
Yes, there is caching.  On my macOS system it in `~/.homebridge/accessories/cachedAccessories`.

Given what you're observing I'll assume the new hardware tells if it has a light or not in a different way than the old one.  If you add these debugging parameters to the config for the 2nd fan, it may log something useful.  If not, the next step would be to log everything the fan sends and try to see which bits tell us about the light.

```
   "debugLevels": [
      ["cluing", 1],
      [ "redflags", 1]
    ]
```
[edited to change["cluing", 0], to ["cluing", 1]]

**Comment by speedlimiter** [comment]
`[14/08/2022, 12:27:43] [BigAssFans-i6] dblog progress(0/0) Haiku Schlafzimmer - product type: Haiku H/I Series (0x48, 0x61, 0x69, 0x6b, 0x75, 0x20, 0x48, 0x2f, 0x49, 0x20, 0x53, 0x65, 0x72, 0x69, 0x65, 0x73)`
`[14/08/2022, 12:27:43] [BigAssFans-i6] dblog progress(0/0) Haiku Schlafzimmer - firmware: 3.1.0`
`[14/08/2022, 12:27:43] [BigAssFans-i6] dblog cluing(1/1) Haiku Wohnzimmer - fell into default, field: "66"`
`[14/08/2022, 12:27:43] [BigAssFans-i6] dblog cluing(1/1) Haiku Wohnzimmer -  value: 1`
`[14/08/2022, 12:27:43] [BigAssFans-i6] dblog cluing(1/1) Haiku Wohnzimmer - fell into default, field: "67"`
`[14/08/2022, 12:27:43] [BigAssFans-i6] dblog cluing(1/1) Haiku Wohnzimmer -  value: 0`
`[14/08/2022, 12:27:43] [BigAssFans-i6] dblog cluing(1/1) Haiku Wohnzimmer - fell into default, field: "85"`
`[14/08/2022, 12:27:43] [BigAssFans-i6] dblog cluing(1/1) Haiku Wohnzimmer -  value: 1`
`[14/08/2022, 12:27:43] [BigAssFans-i6] dblog cluing(1/1) Haiku Wohnzimmer - fell into default, field: "109"`
`[14/08/2022, 12:27:43] [BigAssFans-i6] dblog cluing(1/1) Haiku Wohnzimmer -  value: 0`
`[14/08/2022, 12:27:43] [BigAssFans-i6] dblog cluing(1/1) Haiku Wohnzimmer - fell into default, field 17 message with subfield: "2"`
`[14/08/2022, 12:27:43] [BigAssFans-i6] Haiku Wohnzimmer - no light detected`
`[14/08/2022, 12:27:43] [BigAssFans-i6] dblog cluing(1/1) Haiku Wohnzimmer - fell into default, field: "84"`
`[14/08/2022, 12:27:43] [BigAssFans-i6] dblog cluing(1/1) Haiku Wohnzimmer -  value: 1`
`[14/08/2022, 12:27:43] [BigAssFans-i6] dblog cluing(1/1) Haiku Wohnzimmer - fell into default, field: "176"`
`[14/08/2022, 12:27:43] [BigAssFans-i6] dblog cluing(1/1) Haiku Wohnzimmer -  length: 19`
`[14/08/2022, 12:27:43] [BigAssFans-i6] dblog cluing(1/1) Haiku Wohnzimmer - fell into default, field: "177"`
`[14/08/2022, 12:27:43] [BigAssFans-i6] dblog cluing(1/1) Haiku Wohnzimmer -  length: 16`
`[14/08/2022, 12:27:43] [BigAssFans-i6] dblog cluing(1/1) Haiku Wohnzimmer - fell into default, field: "178"`
`[14/08/2022, 12:27:43] [BigAssFans-i6] dblog cluing(1/1) Haiku Wohnzimmer -  length: 18`
`[14/08/2022, 12:27:43] [BigAssFans-i6] dblog cluing(1/1) Haiku Wohnzimmer - fell into default, field: "179"`
`[14/08/2022, 12:27:43] [BigAssFans-i6] dblog cluing(1/1) Haiku Wohnzimmer -  length: 19`
`[14/08/2022, 12:27:43] [BigAssFans-i6] dblog progress(0/0) Haiku Wohnzimmer - product type: Haiku H/I Series (0x48, 0x61, 0x69, 0x6b, 0x75, 0x20, 0x48, 0x2f, 0x49, 0x20, 0x53, 0x65, 0x72, 0x69, 0x65, 0x73)`
`[14/08/2022, 12:27:43] [BigAssFans-i6] dblog progress(0/0) Haiku Wohnzimmer - firmware: 3.1.0`
`[14/08/2022, 12:27:43] [BigAssFans-i6] dblog cluing(1/1) Haiku Wohnzimmer - fell into default, field 17 message with subfield: "2"`
`[14/08/2022, 12:27:43] [BigAssFans-i6] Haiku Schlafzimmer - light detected`
`[14/08/2022, 12:27:43] [BigAssFans-i6] dblog cluing(1/1) Haiku Wohnzimmer - fell into default, field 152 message with subfield: "5"`

...

`[14/08/2022, 12:28:43] [BigAssFans-i6] dblog cluing(1/1) Haiku Wohnzimmer - fell into default, field 17 message with subfield: "2"`
`[14/08/2022, 12:28:43] [BigAssFans-i6] dblog cluing(1/1) Haiku Wohnzimmer - fell into default, field 152 message with subfield: "5"`
`[14/08/2022, 12:29:43] [BigAssFans-i6] dblog cluing(1/1) Haiku Wohnzimmer - fell into default, field 17 message with subfield: "2"`
`[14/08/2022, 12:29:43] [BigAssFans-i6] dblog cluing(1/1) Haiku Wohnzimmer - fell into default, field 152 message with subfield: "5"`

The last two lines are always repeating. Btw: Is it possible to paste multiple lines of "code" without having to do this with every line? Normally not a GitHub user. ☺️

**Comment by oogje** [comment]
Thanks for the logs.  If I understand correctly, to paste multiple lines of code you could click the "<>" icon above the text box of your new message, then paste in multiple lines,  then move your cursor beyond the closing apostrophe if you want to the more text.

![Screen Shot 2022-08-14 at 12 53 20 PM](https://user-images.githubusercontent.com/1358680/184547050-812bfb06-48d7-4e5a-bf68-3a23ed99d7cd.png)

I've published `homebridge-i6-bigassfans@0.5.2-beta2` which takes a guess about how to identify if your fan has a light.  Can you give that a try using the same debugLevels settings.  If we got lucky and it works there's no need to post the logs and you can remove those settings or change them from '1' to '0'.

If it doesn't work we'll find something else to try.

**Comment by speedlimiter** [comment]
Works! A big thank you for your support

`[14/08/2022, 19:53:57] [BigAssFans-i6] Haiku Wohnzimmer - light detected`

**Comment by oogje** [comment]
My pleasure.  Time will tell if this change broke something 😁.

**Comment by oogje** [comment]
> ... Time will tell if this change broke something 😁.

Hello @speedlimiter,

Time has come today.  It seems this change creates a phantom downlight on some fans (Issue #20 , Issue #28 ). Since you had two fans where only one required this change, it could be very helpful in resolving issue #28 if I had detailed communication logs for each of your two fans to compare how they indicate the presence of a downlight.

At your convenience could you please add the following configuration settings for both fans and restart Homebridge with the -D debug option:
```
"debugLevels": [
      ["network", 11],
      ["redflags", 1]
    ]
```

The logs will contain your MAC address, local LAN IP, and WiFi network name encoded in the hex stream so if you want to email them instead of posting here, you can send to turbo_titled_0w@icloud.com.

If you're using Homebridge-UI you can tell it to use the -D option when restarting homebridge:
![](https://user-images.githubusercontent.com/1358680/202518414-8e6c369c-26bb-48cf-abac-4fea54c2e8bb.png)

Thank you.

**Comment by oogje** [comment]
I no longer need these logs. Thank you.
