### ISSUE TITLE
Unhandled network error: EHOSTUNREACH.  Attempting reconnect in 2 seconds.

### ISSUE THREAD

**Issue by yeo423** [oogje/homebridge-i6-bigAssFans#18]
Started receiving this message after updating to v0.5.2 yesterday for both fans I have installed. 

Attempted a version rollback but same consistent error.  

Also showing both fan and a light for their respective tiles in home app. No light installed on fans and was not showing prior to update.  Can not see where I have selected a light within the plugin either. 

Think a reinstall help alleviate this?

**Comment by yeo423** [comment]
Disregard.  A simple power cycle of the fans resolved the issue. Sorry.

**Comment by oogje** [comment]
Thanks for the feedback.
