### ISSUE TITLE
Plugin incorrectly thinks there's an uplight.

### ISSUE THREAD

**Issue by oogje** [oogje/homebridge-i6-bigAssFans#19]
I am still seeing this issue with the plugin seemingly randomly creating a light for my fans appending "Upight" at the end of the name in Homebridge.. 

I am running v0.5.3 and have two Haiku L fans. Once I installed v0.5.3 I started having the problems discussed above and used the suggestions in this issue to fix by deleting cache etc. Occasionally the names of the two fan lights would change to just "fan" in Home and I would have to rename them and add them back to scenes etc. About 4 days ago I got everything working properly and it seemed stable again. This morning one of my lights was renamed again in Home and I looked in Homebridge and there was a second light with "Upight" appended to the end of the name. While I was looking at this the same thing happened to the other fan. I deleted the cache and rebooted and both of the extra lights were no longer in Homebridge. I then updated Home with the correct names and updated scenes and things are back to normal, or as normal as they get around here.

Are there any other steps I can take on my end to keep this from happening? If am able to send you logs or troubleshoot if you would like.

Thanks in advance.

_Originally posted by @afellows77 in https://github.com/oogje/homebridge-i6-bigAssFans/issues/17#issuecomment-1312755845_

**Comment by oogje** [comment]
@afellows77, at your convenience please try `homebridge-i6-bigassfans@0.5.4-beta1`.

**Comment by afellows77** [comment]
Installed v0.5.4-beta1 and that seems to have resolved this issue. I will keep keep an eye on it and let you know if anything changes.

**Comment by oogje** [comment]
Thanks!

**Comment by afellows77** [comment]
v0.5.4-beta1 appears to have resolved the issue. I have not seen any instances of the "upight" devices in Homebridge even after multiple reboots. 

I also wanted to say thanks for all of your work on this plugin. Without it I would probably be purchasing new fans. Much appreciated!!

**Comment by oogje** [comment]
Thanks for the kind feedback.

**Comment by oogje** [comment]
PS - I just found and fixed the "upight" typo in the source.
