### ISSUE TITLE
Support for haiku model fans?

### ISSUE THREAD

**Issue by pponce** [oogje/homebridge-i6-bigAssFans#2]
Love that you made a plugin for bigassfans.
Any chance you can extend it to work with their other types of fans? Haiku?
I have two of those and can help troubleshoot as needed.  The other plugin for bigassfans does not seem to be actively developed.
I know it’s a long shot since you probably need one of these fans in your possession both for the drive to do it and also to be effective… thought I’d ask anyway. 😄

**Comment by oogje** [comment]
HI.  I hear you.  It would probably be a frustrating project without direct access to a Haiku.  Do you have a unix-based operating system like macOS or Linux?

**Comment by pponce** [comment]
I do have mac laptops and a bunch o rpi’s running Linux.

**Comment by oogje** [comment]
That’s great.  We can try some stuff and see how far we get.

Shall we set up direct contact?  How about emailing me at the address in my GitHub profile?

**Comment by pponce** [comment]
@oogje hey there. So sorry to ask for some feature support and then go completely MIA! I had some large projects take over my time/bandwidth completely.

I can connect directly shortly.
The existing big-ass-fans plugin mostly works. There might be some improvements to how it polls or better yet would be great if it did not need to poll. 
have you taken a look at that project?  My worst fear is that some change to HomeKit or homebridge occurs and breaks the plugin.  Did you want to look at the big-ass-fans api and see if you can add support based on the code you see there? I can then do some testing?

I’ll email you shortly if you are still up for giving this ago.

**Comment by oogje** [comment]
I'm still up for looking into it.

I have looked at the big-ass-fans api but I really didn't understand it well enough to change it.  As far as I can tell the Haiku fans communicate in plain text while the i6 fans speak binary.  I thought it would be straightforward to change the low level communication but, for me it wasn't so I started out fresh with the homebridge tutorials using typescript. 

I would think if some change to homekit/homebridge breaks the plugin it shouldn't be too hard to repair it.  I assume enough  plugin developers will be in the same boat that fixes will be reasonably well documented.  Maybe by then the manufacturer will have their own plugin.

My approach would be to start by using "nc" to connect to your fan and see if you can turn it off and on and then build from there.

As far is polling, I don't know if you can avoid that, but maybe.

**Comment by oogje** [comment]
Closing this now since pponce and I are in contact.
