### ISSUE TITLE
Additional switches all have the same name

### ISSUE THREAD

**Issue by BradJMelb** [oogje/homebridge-i6-bigAssFans#21]
Fan: Haiku I Series
Firmware: 3.1.1
Plugin version 0.5.3

Hi there,
I set up my Haiku I today and after updating the firmware to 3.1.1 everything started working in the Home app.
I noticed though that each of the additional switches all default to having the same name in Home.app

In my case they were all "Master Bedroom Fan" which is the fan name that I specified in the config file. I turned each of the functions on one by one and checked the state in the BAF app and then renamed them which was fine but it would be nice if they each had unique names when they first get added to HomeKit.

The switches I enabled were:
                    "showWhooshSwitch": true,
                    "showFanAutoSwitch": true,
                    "showLightAutoSwitch": true,
                    "showEcoModeSwitch": true

I then tried grouping each of these switches together which wasn't a good idea because HomeKit wouldn't allow me to ungroup them once I worked out that it wasn't going to do what I wanted (the ungroup button wouldn't show). I was hoping to just group those switches together in one tile but then have the 4 switches show when tapping on the tile but I've now learned that's not how HomeKit works with groups.

I have the Home+ app installed and I was able to ungroup from within it but I wondered if it was because they all had the same name initially that I had troubles ungrouping them.

Using the show as a single tile doesn't work for me as I'd still like to have the fan and light as separate tiles and then the advanced options all on one tile.

Great job on the plugin, other than this little hiccup, it's all working very well so far.

Thanks,
Brad.

**Comment by oogje** [comment]
Hello.  `homebridge-i6-bigassfans@0.5.4-beta4` addresses this naming issue brought on by iOS/iPadOS 16.  Since you've already done the work to rename the switches, there might not be any benefit for you. 

To look at the grouping issue, using the beta, I created a group of five switches.  When I view at the Accessory Details of this switch group, I can select Accessories, then edit and add or remove accessories from the group.  There's no "Ungroup accessories" button like there is for other groups in my Home app.  I don't know why that button would appear on some accessories and not others.

**Comment by BradJMelb** [comment]
Thanks for the feedback. I just got my second Haiku fan so I was able to test the fix for the naming issue in the beta release. It works much better now.

Don't worry about the grouping stuff, that's definitely a HomeKit oversight.

I'll mark this as closed.

Thanks again,
Brad.

**Comment by oogje** [comment]
Thanks for following up.

**Comment by BradJMelb** [comment]
Just wanted to ask if it's possible to cache the custom names if you rename from the default? I find that if I restart home bridge my custom names go back to the defaults that you set in beta 0.5.4 beta 4.

Thanks!

**Comment by oogje** [comment]
I didn't realize (or maybe I didn't remember) that was happening until I reproduced the issue just now.  I'll look into and see if I can figure out what's going on.

**Comment by oogje** [comment]
I think `homebridge-i6-bigassfans@0.5.4-beta9` fixes the name persistence problem.

**Comment by BradJMelb** [comment]
> I think `homebridge-i6-bigassfans@0.5.4-beta9` fixes the name persistence problem.

I've updated to b9, restarted homebridge and tried again but after renaming "Master Bedroom Fan Light" to "Fan Light" in the Home app and restarting homebridge then the name still goes back to Master Bedroom Fan Light.

Should I be seeing something change in the persist folder or the accessories/cachedAccessories file?

Thanks,
Brad.

**Comment by oogje** [comment]
Hmm.   Back to the drawing board.  🤔
[edited to add] No need to look at files at this point.

**Comment by oogje** [comment]
For your consideration - homebridge-i6-bigassfans@0.5.4-beta10

**Comment by BradJMelb** [comment]
Thanks for the update @oogje, unfortunately it's still the same. The steps I'm taking to reproduce are:
1. Update to the latest beta
2. Restart homebridge
3. Rename one of the items (fan light in this case)
4. Restart homebridge
5. Check the name again in Home.app, find that it has reverted to the default.

Thanks.

**Comment by oogje** [comment]
Does renaming one or more of the switches survive a reboot?
[edited to add] ... rather than the light switch

**Comment by BradJMelb** [comment]
No, I’ve tried them all and the behaviour is the same.

After renaming:
![IMG_3803](https://user-images.githubusercontent.com/52709423/233764125-95b9de17-1004-4f28-8c27-2aa254720a0e.jpeg)

And after rebooting:
![IMG_3804](https://user-images.githubusercontent.com/52709423/233764126-d021d40c-f3c3-42a4-9cad-8cf9bb6303b9.jpeg)

**Comment by oogje** [comment]
Do you want to try removing the cache via Homebridge UI?  This presumably will also remove the fan from your scenes and automations and place it in the default room.

**Comment by aveach** [comment]
Wondering if this isn't a larger Homebridge/HomeKit problem atm... I have another Homebridge device through another plugin (unifi-smartpower) that just would not keep the new name, even after renaming multiple times. 

I removed that device from any automations I had, then renamed it, and now it seems that the name is sticking.

**Comment by oogje** [comment]
@aveach, are you seeing the issue @BradJMelb has with the bigassfans plugin?
