### ISSUE TITLE
Expose motion detection information

### ISSUE THREAD

**Issue by aveach** [oogje/homebridge-i6-bigAssFans#23]
The es6 (and others I believe) have motion detection for their "auto" features. Would be cool to have this exposed to HomeKit so you can trigger things off of detected motion/persons.

**Comment by oogje** [comment]
Hello.  We can try to see if the fan notifies us when it detects motion.  Can you set the network debugLevels to 11 like you did previously and capture the logs when there's been no motion in the room, then trigger the motion sensor, noting the time, and  we'll see if anything is different in the messages.

**Comment by oogje** [comment]
I should add, when you do that, please email me the logs.

**Comment by aveach** [comment]
Haha of course! Sorry, just haven't gotten a second to grab logs. It's on my mind though!

**Comment by thicla01** [comment]
Hello oogje, aveach,

I found this information for the Big Ass Fan integration in Home Assistant (https://www.home-assistant.io/integrations/baf/#binary-sensor): 

> **Binary Sensor**
> 
> For devices that support Auto Comfort and are running firmware 3.1 or later, an occupancy sensor entity is available. The sensor has a hold time of about 5 minutes and pushes state updates.
> 

You may also look at : https://github.com/home-assistant/core/blob/dev/homeassistant/components/baf/binary_sensor.py

**Comment by oogje** [comment]
@thicla01 ,

That's encouraging.  Thanks.

**Comment by thicla01** [comment]
Hello oogje,

I configure my Haiku fan to Fan Auto with Motion Timeout at 1 min. Here is some logs about that:

- [24/01/2023, 12:05:59] [homebridge-i6-bigassfans] dblog characteristics(3/3) Haiku Chambre - update FanOn: true because (auto && speed > 0)
- [24/01/2023, 12:07:04] [homebridge-i6-bigassfans] dblog characteristics(3/3) Haiku Chambre - update FanOn: false because (auto && speed == 0)

Now with Timeout at 2 min. (No movement in the room between 12:14:08 and 12:16:16)

- [24/01/2023, 12:14:08] [homebridge-i6-bigassfans] dblog characteristics(3/3) Haiku Chambre - update FanOn: true because (auto && speed > 0)
- [24/01/2023, 12:16:16] [homebridge-i6-bigassfans] dblog characteristics(3/3) Haiku Chambre - update FanOn: false because (auto && speed == 0)

Now with Timeout at 2 min. Movement around 12:19 and 12:20 and no movement after that

- [24/01/2023, 12:18:59] [homebridge-i6-bigassfans] dblog characteristics(3/3) Haiku Chambre - update FanOn: true because (auto && speed > 0)
- [24/01/2023, 12:22:10] [homebridge-i6-bigassfans] dblog characteristics(3/3) Haiku Chambre - update FanOn: false because (auto && speed == 0)

Let me know if you need more complete logs

**Comment by oogje** [comment]
Hi thicla01,

I'd like to see the network traffic in order to look for clues that might indicate a message regarding the motion/occupancy sensor.

Can you set the network debug level to 11 (`"network", 11`) in the config file and rerun your scenarios?

Thanks.

**Comment by oogje** [comment]
Here's and example of the per fan debug log settings for the config.json file:

`"debugLevels": [
                        [
                            "redflags",
                            1
                        ],
                        [
                            "network",
                            11
                        ]
                    ]`

**Comment by thicla01** [comment]
Hello oogje,

Logs sent to turbo_titled_0w@icloud.com

**Comment by oogje** [comment]
> Logs sent to [turbo_titled_0w@icloud.com](mailto:turbo_titled_0w@icloud.com)

Got them, thanks!

**Comment by oogje** [comment]
Hello  thicla01,

If you add:
	`[ “newcode”, 1 ]`
to your _debugLevels_ and run `homebridge-i6-bigassfans@0.5.4-beta7` you should see messages like:

_occupancy: 1 detected per field: 66
occupancy: 0 detected per field: 85_

where fields _66_ and _85_ are thought to be _fan_occupancy_detection_ and _light_occupancy_detection_ by the “Python async IO library for Big Ass Fans i6 firmware”, which I believe is used by Home Assistant.

You can set any of the other debugLevels parameters to 0 to get rid of the verbose messages.

Do you see a relationship between your movements and these messages?

Thanks!

**Comment by thicla01** [comment]
Hello oogje,

Yes, it's working! I'm running out of time to complete all the tests tonight, but I'll do some more tests tomorrow and send you the logs.

Have a good evening

**Comment by oogje** [comment]
Sounds good. No hurry.

**Comment by thicla01** [comment]
Logs sent

**Comment by oogje** [comment]
Thank you!

**Comment by thicla01** [comment]
It's also working with the old Wall Control

**Comment by oogje** [comment]
`homebridge-i6-bigassfans@0.5.4-beta8` enables occupancy sensors per the config settings:

**"showFanOccupancySensor": true**
and
**"showLightOccupancySensor": true**

Let's see how this work out.

**Comment by aveach** [comment]
@thicla01 @oogje: y'all rock! Thanks for picking up my slack and collecting the logs/getting the feature done! I'll try out the beta tonight.

**Comment by thicla01** [comment]
Thank you aveach

@oogje I installed the beta version 8. I removed my Haiku fan from Homebridge and Homekit, cleared the cache, restarted homebridge, reconfigured the Haiku fan, restarted Homebridge again. I added the Haiku fan in Homekit. I don't see the occupency sensor. In the logs I see the occupancy sensors are working in Homebridge.

Here is my configuration
"fans": [
                {
                    "name": "Haiku Chambre",
                    "ip": "192.168.X.XXX",
                    "mac": "XX:XX:XX:XX:XX:XX",
                    "fanModel": "Haiku H/I Series",
                    "showWhooshSwitch": false,
                    "showFanAutoSwitch": true,
                    "showLightAutoSwitch": true,
                    "showDimToWarmSwitch": false,
                    "showEcoModeSwitch": true,
                    "disableDirectionControl": true,
                    "debugLevels": [
                        [
                            "network",
                            0
                        ],
                        [
                            "redflags",
                            0
                        ],
                        [
                            "characteristics",
                            0
                        ],
                        [
                            "newcode",
                            1
                        ]
                    ]
                }

**Comment by oogje** [comment]
I don't see
`"showFanOccupancySensor": true`
or
`"showLightOccupancySensor": true`
in your config.  You'll need one or both to see a sensor.

**Comment by thicla01** [comment]
Ha OK! Sorry, I missed your instructions above. Now both occupancy sensors are added to homekit and are working!
I even created an automation with one of the occupancy sensor and the automation worked.

Let me know if you want specific tests.

**Comment by oogje** [comment]
That’s great. Thanks for your help!  Going forward just use it for a while and if meets your and @aveach’s needs it’ll be part the next release.

**Comment by thicla01** [comment]
OK, I will try some automations in the living room also. I will let you know.

**Comment by aveach** [comment]
This is working for me, thanks! 

One thought, is there any benefit to showing (or even giving the option of) each separate occupancy sensor? Seems like we should just pick one (or OR them) and just show a single occupied or not.

**Comment by oogje** [comment]
Thanks for the update, @aveach.

In the logs I've seen the fan and light occupancy sensors (if that's truly what they are) seem to closely mirror each other but not exactly.  So I want to keep them both as options until I test out all the possible "auto" options to see if changing the "comfort", "motion", "thermostat" and "return to auto" settings of the fan effects what we think is the motion sensor for the light, and likewise changing the light "auto" settings effects the fan motion sensor.

**Comment by thicla01** [comment]
Hello, each occupancy sensor have a different timeout period in BAF app. Better to keep them separate. Is it possible to expose the Timeout of the occupancy sensors in HomeKit?

**Comment by thicla01** [comment]
Another thing is that, you can deactivate one of the occupancy sensor (let say for the Fan) and keep the other one active in the BAF app.

**Comment by thicla01** [comment]
One of my automation to control other lights in the same room where is the Haiku Fan look like this:

If Haiku Chambre Light Occupancy detected is yes
Then 
    If Haiku Chambre Light Auto Is activated
       Then set accessory light Hue to 30%
       Else do nothing
Else do nothing

**Comment by oogje** [comment]
> Is it possible to expose the Timeout of the occupancy sensors in HomeKit?

I've looked a bit and don't see how I would implement it.  Having said that it's almost certainly possible.  The question is how much of a hack would it be.

**Comment by thicla01** [comment]
I thought it might be difficult. :/

**Comment by oogje** [comment]
> I thought it might be difficult. :/

Yeh, I've been trying different things with no luck and at this point, other than an eleven bit number represented as eleven switches to indicate the number of minutes of the timeout, I'm out of ideas.

**Comment by thicla01** [comment]
Hello oogje, About my last request, thanks for trying. :)

What you have done for the occupancy sensors works very well. Let me know if you need more testing.

**Comment by oogje** [comment]
Thanks!  If issues arise with the occupancy sensors I'll be glad to have your help.
