### ISSUE TITLE
Disabled fan direction shows up in Homekit

### ISSUE THREAD

**Issue by stefanolarentis** [oogje/homebridge-i6-bigAssFans#25]
Hi all,

great plugin. Even though I disabled direction control in the plugin settings, direction control still shows up in Homekit.

I am using latest non beta version of plugin and homebridge. Otherwise the plugin is rock solid.

**Comment by oogje** [comment]
As it stands, I don't know how to remove the direction control.  If you disable the control in your configuration then tapping on it should not change fan direction. Let me know if the fan is changing direction when you have `"disableDirectionControl": true` and we can investigate.

**Comment by stefanolarentis** [comment]
You are right, the switch has no effetct. It is just a bit confusing. Maybe somebody can chime in on home to remove it.
Cheers

**Comment by oogje** [comment]
One can hope.
