### ISSUE TITLE
Turning on light via Siri turns on fan as well

### ISSUE THREAD

**Issue by mathewthomas1721** [oogje/homebridge-i6-bigAssFans#26]
I have a Haiku L series fan with a light. I’ve separated the light from the fan in HomeKit, but when I ask Siri to turn on the light, it turns on the light as well. Not sure if bug or I’m doing something wrong

**Comment by aveach** [comment]
@mathewthomas1721 I'm fairly sure this is a HomeKit issue with the way it parses the name. I had to rename my light without using any indication of "fan" and now it works to turn on solely the light.

**Comment by oogje** [comment]
@mathewthomas1721, I have also separated the fan and the light. My fan is named Big Fan and my light is named Big Fan Light. When I tell Siri “Hey Siri, turn on the big fan light”, only the light comes on. 

What is your fan named? What is is your light named? What exactly are you saying to Siri and can you see what Siri thinks you’re saying?

**Comment by mathewthomas1721** [comment]
My setup is as follows : 
The fan is named Bedroom Ceiling Fan, the light is named Bedroom Ceiling Light. Bedroom Ceiling Fan is an individual device, while Bedroom Ceiling Light is grouped with all the lights in the room in a group called Bedroom Lights. 

Saying “Hey Siri, turn on the Bedroom Lights” turns on all the lights including Bedroom Ceiling Light, but also turns on Bedroom Ceiling Fan. 

I’d be happy to check what Siri thinks I’m saying, how can I go about doing that?

**Comment by oogje** [comment]
It sounds like Siri is correctly interpreting what you're saying.  For what it's worth when I speak to Siri using my iPhone it shows the text of what it hears as I speak. 

I've never used groups so I don't know how that might play into this.  What happens if you say "Hey Siri, turn on the Bedroom Ceiling Light"?

**Comment by mathewthomas1721** [comment]
So it seems like it only messes up when I group the Ceiling Light with the
other lights. Treating it as an individual device, it seems to work fine.
My theory is, when I say, "Hey Siri, turn on the Bedroom Lights", it's
actually just hearing "Hey Siri, turn on the Bedroom", and turning on
everything in the bedroom.

Thank you for the help, I'll close this issue, clearly this is not a plugin
problem.

**Comment by oogje** [comment]
Thanks for following through.
