### ISSUE TITLE
Permit changing of device icon in Homekit

### ISSUE THREAD

**Issue by ed-ong** [oogje/homebridge-i6-bigAssFans#27]
**Is your feature request related to a problem? Please describe:**
The fan device icon appears as a standing desk fan in the Home app. The icon cannot be changed to the "ceiling fan" icon.

**Describe the solution you'd like:**
Permit changing of the device icon in Homekit.

**Additional context:**
In the Home app, smart switch icons can be changed to show the device it controls e.g. light, standing fan, ceiling fan, etc.

**Comment by oogje** [comment]
Hello,

On a Mac running macOS Mojave (10.14.5) I have the same experience as you have.  But on a Mac running Ventura 13.1, or an iPhone with iOS 16.3 I am able to select a ceiling fan icon from a choice of three (standing, desk and ceiling).

What version of your device's operating system are you running.

**Comment by ed-ong** [comment]
Hello, 

I am using an iPhone 13 Pro Max running iOS 16.3. My fan is a Haiku H/I Series.
The issue is replicated on an iPhone X running iOS 16.2 and an iPad Air running iPadOS 16.3.

**Comment by oogje** [comment]
I don't know what's causing this issue.  I'll ask around and do some experimentation. 

Which version of the plugin are you using?   Was the problem always present or did it show up only after a plugin update?  Which version of Homebridge are you running?

Thanks.

**Comment by oogje** [comment]
Also, are you using a child bridge?

**Comment by ed-ong** [comment]
Homebridge version: v1.6.0
Plugin version: v0.5.3
This is the only version of the plugin I have used (first installed last week), so I am unable to tell if it's an issue that started after an update.
I just tried setting the plugin as a child bridge, and unfortunately the problem persists.

Thanks!

**Comment by oogje** [comment]
Are you displaying the fan and possibly its lights and switches in HomeKit as a single tile or separate tiles?  When I show mine as a single tile it appears to lock the icon.

**Comment by ed-ong** [comment]
My fan doesn’t have lights but setting “showTemperature” to False fixes the issue! Looks like exposing the temperature sensor to HomeKit locks the icon?

**Comment by ed-ong** [comment]
After changing the icon, re-enabling the temperature sensor locks the icon to the new icon.

**Comment by oogje** [comment]
That's good. It seems there's no concept of a separate tile for the sensor(s).  But the locking behavior acts as if it's a single tile.

[edited to remove question about separate tiles]

**Comment by oogje** [comment]
PS - that was a great idea to disable the temperature sensor

**Comment by oogje** [comment]
Hello. I've looked into this and it seems the best way for me to deal with the issue would be for the plugin to treat the fan and all the switches and sensors as individual accessories.  I imagine that could be done in a configurable way but to be frank, given there is a relatively easy workaround, I'm not keen to put in the effort.

**Comment by ed-ong** [comment]
I agree, maybe a brief note in the readme about the workaround might suffice

**Comment by oogje** [comment]
Sounds good.  This is what I propose to add to the readme.  Let me know if you have notes.

### **Other**

If you find you cannot change the fan icon in Apple's Home app and you are showing your fan with its lights and/or switches as a single tile, then show it as separate tiles.  That should unlock the icon so you can change it, then set it back to **Show as Single Tile** and the icon will be locked with your change in effect.

In some cases the Home app doesn't have the option to **Show as Separate Tiles** or **Show as Single Tile** in the Fan's settings, e.g. a Haiku H/I with no light and no optional switches being shown.  In this case the work-around is to add `"showTemperature": false` to your  config.json for the fan, restart, then change the icon, then remove the `"showTemperature"` line or change the setting to `true`, and restart.

**Comment by ed-ong** [comment]
Looks great!

**Comment by oogje** [comment]
Okey doke.  The readme is updated now.  Thanks for your help.
