### ISSUE TITLE
Detecting an uplight when one does not exist

### ISSUE THREAD

**Issue by knmorgan** [oogje/homebridge-i6-bigAssFans#31]
**Describe The Bug:**
As the title says. My fan has a downlight but no uplight, and the plugin is detecting both. Sort of the opposite problem of #28.

**To Reproduce:**
This is a Haiku Gen 4 with a downlight and no uplight.

Reading #28, I attempted to set `uplightEquipped` to `false`, but this does not appear to do anything. It still detects the uplight in the homebridge logs and still presents the false switch in Homekit.

**Expected behavior:**
No uplight switch for fans that do not have one. At least an option to disable it.

**Logs:**

```
[09/10/2023, 12:46:44] [BigAssFans-i6] Main Room Fan - uplight detected
```

**Plugin Config:**

```
        {
            "fans": [
                {
                    "name": "Main Room Fan",
                    "ip": "192.168.5.1",
                    "mac": "ab:cd:ef:12:34:56",
                    "fanModel": "Haiku H/I Series",
                    "showWhooshSwitch": false,
                    "showFanAutoSwitch": false,
                    "showLightAutoSwitch": false,
                    "showDimToWarmSwitch": false,
                    "showEcoModeSwitch": false,
                    "disableDirectionControl": true,
                    "uplightEquipped": false
                }
            ],
            "platform": "BigAssFans-i6"
        }
```

**Screenshots:**
N/A

**Environment:**

* **Plugin Version**: 0.5.4
* **Homebridge Version**: 1.6.1
* **Node.js Version**: 16.14.0
* **NPM Version**: 
* **Operating System**: Raspbian

**Comment by oogje** [comment]
Hello.  Could you try `homebridge-i6-bigassfans@0.6.0-beta4`.

**Comment by knmorgan** [comment]
I installed beta6 and it seems to fix the issue. When is 0.6.0 coming out of beta?

**Comment by oogje** [comment]
> When is 0.6.0 coming out of beta?

I don't know.  I tend to drag my feet when it comes to making something a "release".  Before I make a 0.6.0 I think I'd want to remove the post-beta4 hacks as I don't know if they work and have no way to test them myself.

Would having a 0.6.0 be useful to you or were you asking out of curiosity?

**Comment by knmorgan** [comment]
> Would having a 0.6.0 be useful to you or were you asking out of curiosity?

It's just a psychological thing -- I'd prefer not to run a beta plugin.

**Comment by oogje** [comment]
Okay.  We'll leave this issue open until 0.6.0 is pushed out?

**Comment by knmorgan** [comment]
I can close now; I appreciate the help!
