### ISSUE TITLE
Hi from Germany. I migrated my Haiku Ceiling Fan, I Series to the Big Ass Fans app and FW 3.0.0 and switched to your plugin v0.3.14-beta.

### ISSUE THREAD

**Issue by oogje** [oogje/homebridge-i6-bigAssFans#4]
Hi from Germany. I migrated my Haiku Ceiling Fan, I Series to the Big Ass Fans app and FW 3.0.0 and switched to your plugin v0.3.14-beta.
At first, it worked, but then I see this line in the log and the fan is not responding anymore.

`[15.4.2022, 07:31:46] [BigAssFans-i6] Fan configured with ip: xxx.xxx.xxx.xx is not responding to our probe.  This could happen if the fan model is not i6, but for instance Haiku.`

Homebridge and all other plugins are running. Only restart the Homebridge makes the Fan available again.
I will have an eye on it.

@oogje Thanks for your time and work, sharing with the community and for the ongoing development.

_Originally posted by @DJay-X in https://github.com/oogje/homebridge-i6-bigAssFans/issues/3#issuecomment-1099872387_

**Comment by oogje** [comment]
Hello @DJay-X,

I copied your comment to a new thread so we can dig into the problem you're seeing.

I need to change that message because it's confusing now that the plugin is going to support Haiku fans too.

Can you post the fans section of your config.json?

**Comment by DJay-X** [comment]
Thanks a lot.

```
{
            "fans": [
                {
                    "name": "Deckenventilator",
                    "ip": "xxx.xxx.xxx.xx",
                    "mac": "12:A3:4B:XX:XX:XX",
                    "whoosh": true,
                    "dimToWarm": false,
                    "fanAuto": true,
                    "lightAuto": false
                }
            ],
            "platform": "BigAssFans-i6"
        }
```

**Comment by oogje** [comment]
I don't see any problem with the config.json.  

Are you running homebridge with debugging (-D) on?  I'd like to see any other messages in the logs related to this plugin.

**Comment by DJay-X** [comment]
I will have an eye on how it works in the next days. Currently, no issue for the past hours. 
Also updated to v0.3.15-beta just now.
In the log nothing strange.

```
[15.4.2022, 10:32:05] [BigAssFans-i6] Initializing BigAssFans-i6 platform...
[15.4.2022, 10:32:05] [BigAssFans-i6] Finished initializing platform
[15.4.2022, 10:32:05] [BigAssFans-i6] Loading accessory from cache: Deckenventilator
[15.4.2022, 10:32:05] [BigAssFans-i6] Executed didFinishLaunching callback
[15.4.2022, 10:32:05] [BigAssFans-i6] Init - initializing devices
[15.4.2022, 10:32:05] [BigAssFans-i6] Restoring existing accessory from cache: Deckenventilator
```

**Comment by oogje** [comment]
👍

**Comment by DJay-X** [comment]
Thanks @oogje Everything looks fine. 
Using 0.3.18-beta.1 and the days before the 0.3.17-beta

I only did see this line from time to time.
And in general, there is no humidity showing up in the Home/Eve app.
I don't even know where the temp and RH should come from. 😅
However, Temp is showing. 

```
[17.4.2022, 08:51:22] [BigAssFans-i6] current relative humidity out of range: 1000, ignored
[17.4.2022, 09:08:20] [BigAssFans-i6] current relative humidity out of range: 1000, ignored
[17.4.2022, 09:15:19] [BigAssFans-i6] current relative humidity out of range: 1000, ignored
[17.4.2022, 09:24:18] [BigAssFans-i6] current relative humidity out of range: 1000, ignored
```

**Comment by oogje** [comment]
Hiya.  Apparently Haikus report humidity (or temperature) values as 1000 to mean they don't support this function.

Temperature (again) apparently comes from the remote control.

homebridge-i6-bigassfans@0.3.19-beta should take care of the humidity messages.

I'm curious how your fan reports its model name.  That beta should print it very early on.  If you run the new beta could you please post the log message.

Thanks!

**Comment by pponce** [comment]
@DJay-X My haiku H/I series fans report temp from the fan itself. I have IR remotes and those don’t have temp/humidity sensors. I think they moved to Bluetooth remotes for the i6 series and in those they have humidity and temp sensors.

There is a chance bigassfans enables sending correct humidity values for the haiku fans. It might just be a bug as their documentation states these fans do have a humidity sensor,

**Comment by DJay-X** [comment]
Thanks for the background info. 
However, I doubt that my simple IR remote, and that's the only one I have, has a temp sensor build in. :)

Maybe a `"temp": false` could also be useful if possible. 

![IMG_8675](https://user-images.githubusercontent.com/3874239/163724075-ed9586c1-558d-4a2b-8779-f8a190fc896a.jpeg)


I hope this helps. Thanks again for your work.
```
[17.4.2022, 18:34:21] Loaded plugin: homebridge-i6-bigassfans@0.3.19-beta
[17.4.2022, 18:34:21] Registering platform 'homebridge-i6-bigassfans.BigAssFans-i6'
[17.4.2022, 18:34:24] [BigAssFans-i6] Init - initializing devices
[17.4.2022, 18:34:28] [BigAssFans-i6] Restoring existing accessory from cache: Deckenventilator
[17.4.2022, 18:34:28] [BigAssFans-i6] model: Haiku H/I Series (0x48, 0x61, 0x69, 0x6b, 0x75, 0x20, 0x48, 0x2f, 0x49, 0x20, 0x53, 0x65, 0x72, 0x69, 0x65, 0x73)
[17.4.2022, 18:34:28] [BigAssFans-i6] firmware: 3.0.0
[17.4.2022, 18:34:29] [BigAssFans-i6] no light detected
[17.4.2022, 18:34:29] [BigAssFans-i6] current relative humidity out of range: 1000, assuming no humidity sensor for model "Haiku H/I Series"
[17.4.2022, 18:34:29] [BigAssFans-i6] no such logging tag: "redflags", the message from Deckenventilator is: "ignoring chunk with sole message: 0x12, 0x03, 0xda, 0x0a, 0x00"
```

**Comment by pponce** [comment]
Is the correct temp showing up for you in the home app? and does it show up in the BAF app with the correct temp?
I agree there is no temp/humidity sensor in the IR remotes.  But I believe there is in the fan itself.
http://guides.haikuhome.com/files/i-series/HaikuHome_ISeries.pdf
"Onboard Sensors — Ambient and surface temperature, relative humidity, and passive infrared sensors enable SenseME technology"

**Comment by oogje** [comment]
@DJay-X , alas, that beta was _supposed_ to eliminate the "humidity out of range".   
I'm not sure what you mean by `"temp": false`.  In any event I'll try to tackle the erroneous message again.  And thanks for logs, very helpful.  

@pponce, thanks for the clarification.

**Comment by DJay-X** [comment]
`"temp": false` to use in the config. If someone prefers not to see the temp in HomeKit exposed.

**Comment by oogje** [comment]
Ah, I see what you mean. Do _you_ not want to see the temperature?

[edited to change words]

**Comment by DJay-X** [comment]
I think for the user to have the option to turn it off/hide it, is always a good thing. In my case, I already have temp sensors in the room and the more you have, all of them show some differences. Too much of anything can make you sick. ;)

**Comment by oogje** [comment]
I see your point.  I'll add that feature to the list.

**Comment by thicla01** [comment]
Thank you so much for your great works. My 2 Haiku fans are back in homekit now. 👍

**Comment by oogje** [comment]
Glad to hear it.  Thanks.

**Comment by DJay-X** [comment]
@oogje From my side, everything seems to be working well now. v0.4.1 
This ticket can be closed if you like. Thanks again for your time and work.

**Comment by oogje** [comment]
Thanks for the update @DJay-X.  I'll leave this open until I deliver a `showTemperature: false` setting.

**Comment by DJay-X** [comment]
Updated to v0.4.2. In Config UI is no setting for `showTemperture` so I put it manually in the config.
However, Temp is still showing up in HomeKit.

```
{
            "fans": [
                {
                    "name": "Deckenventilator",
                    "ip": "xxx.xxx.xxx.xx",
                    "mac": "12:A3:4B:XX:XX:XX",
                    "fanModel": "Haiku H/I Series",
                    "whoosh": true,
                    "fanAuto": true,
                    "lightAuto": false,
                    "dimToWarm": false,
                    "ecoMode": false,
                    "showTemperature": false
                }
            ],
            "platform": "BigAssFans-i6"
        }
```

**Comment by oogje** [comment]
For now, try removing `.homebridge/accessories/cachedAccessories` from your home directory.  I'll try to make that unnecessary as of a future release.

**Comment by oogje** [comment]
Also, restart Homebridge after removing the cache file.

**Comment by pponce** [comment]
@DJay-X im paranoid with deleting those files.
I’ve in the past had to reset all my accessories in terms of rooms and automations.
If you are using the plugin as a bridged accessory you should be able to delete just the specific accessories file for this plugin.

I may be wrong though about deleting the shared cachedAccesories file. Maybe it’s safe.

**Comment by oogje** [comment]
I can publish a beta of the next release and you could try that if you like instead of removing the cache file.

**Comment by oogje** [comment]
Note that when you use `"showTemperature": false` the temperature doodad will be removed from any automations, etc.

**Comment by oogje** [comment]
I've pushed out `homebridge-i6-bigassfans@0.4.3-beta1` which should eliminate the need to remove any cache files.

**Comment by DJay-X** [comment]
`"showTemperature": false` manually set in the config.json and restart Homebridge, did now hide the temperature without removing any cache file. 👍

**Comment by oogje** [comment]
Thank you.
