### ISSUE TITLE
Haiku I-series fan light should not advertise color-changing

### ISSUE THREAD

**Issue by jmissig** [oogje/homebridge-i6-bigAssFans#7]
**Describe The Bug:**
Haiku I-series light control has controls for changing the color. This light only has adjustable brightness, not color.

**To Reproduce:**
Add a Haiku I-series fan with light. Open Home app, open fan light controls. There will be a white temperature selector which does not function.

**Expected behavior:**
Light dim-only controls.

**Logs:**

```
Show the Homebridge logs here, remove any sensitive information.
```

**Plugin Config:**

```json
                {
                    "name": "Master Bedroom Overhead Fan",
                    "ip": “xxx",
                    "mac": “xxx",
                    "whoosh": false,
                    "dimToWarm": false,
                    "fanAuto": false,
                    "lightAuto": false
                },
```

**Screenshots:**

![IMG_2656](https://user-images.githubusercontent.com/1448107/164814197-1203d0cc-99c9-4d50-ae7c-b1d7eba1bc86.jpeg)

**Environment:**

* **Plugin Version**: 0.4.1
* **Homebridge Version**: 1.4.0
* **Node.js Version**: v12.22.12
* **NPM Version**: 6.14.16
* **Operating System**: Ubuntu 20.04

**Comment by oogje** [comment]
Thanks for this.  Shouldn't be a problem to fix (famous last words).

**Comment by oogje** [comment]
@jmissig, at your convenience please check if v0.4.2 takes care of this issue.  Thanks.

**Comment by jmissig** [comment]
@oogje correct, fixed now, thanks 🙏🏼!
